apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: apigee-proxy-deployer
  namespace: argo
spec:
  serviceAccountName: argo-workflow 
  entrypoint: main
  
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  templates:
    - name: main
      inputs:
        parameters:
          - name: repo_url
          - name: proxy_path  # Changed to match your command
          - name: apigee_env
      dag:
        tasks:
          - name: clone-code
            template: git-clone
            arguments:
              parameters:
                - name: url
                  value: "{{inputs.parameters.repo_url}}"

          - name: maven-deploy
            dependencies: [clone-code]
            template: apigee-deploy
            arguments:
              parameters:
                - name: apigee_env
                  value: "{{inputs.parameters.apigee_env}}"
                - name: path
                  value: "{{inputs.parameters.proxy_path}}"

    # STEP 1: GIT CLONE
    - name: git-clone
      inputs:
        parameters:
          - name: url
      container:
        image: alpine/git:latest
        workingDir: /src
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-creds
                key: token
          - name: GITHUB_USER
            valueFrom:
              secretKeyRef:
                name: github-creds
                key: username
        command: [sh, -c]
        args: 
          - |
            set -e
            echo "--- Cleaning workspace ---"
            rm -rf ./* .[a-zA-Z]* || true
            
            echo "--- Cloning repository ---"
            REPO_PATH=$(echo "{{inputs.parameters.url}}" | sed 's~https://~~')
            git clone "https://${GITHUB_USER}:${GITHUB_TOKEN}@${REPO_PATH}" .
        volumeMounts:
          - name: workdir
            mountPath: /src

    # STEP 2: APIGEE DEPLOYMENT
    - name: apigee-deploy
      inputs:
        parameters:
          - name: apigee_env
          - name: path
      container:
        image: maven:3.8.5-openjdk-11
        # FIX: Dynamically set the working directory to the proxy folder
        workingDir: /src/{{inputs.parameters.path}}
        command: [sh, -c]
        args:
          - |
            set -e
            echo "--- 1. Fetching Token ---"
            TOKEN=$(curl -s -H "Metadata-Flavor: Google" \
              "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" \
              | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4)

            if [ -z "$TOKEN" ]; then echo "Token failed"; exit 1; fi

            echo "--- 2. Deploying from {{inputs.parameters.path}} ---"
            mvn clean install -P{{inputs.parameters.apigee_env}} \
              -Dtoken="$TOKEN" \
              -Dapigee.options=update \
              -Dapigee.config.options=none \
              -DskipTests=true
        volumeMounts:
          - name: workdir
            mountPath: /src
